<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', {$gakey}]);
  _gaq.push(['_trackPageview']);
  
  {if isset($order) && !empty($order)}

  _gaq.push(['_addTrans',
    {$order->id},           // order ID - required
    'Mercatores',  // affiliation or store name
    {$order->cena},          // total - required
    0,           // tax
    {$order->dodani},              // shipping
    {$order->mesto},       // city
    '',     // state or province
    {$order->stat}             // country
  ]);

   // add item might be called for every item in the shopping cart
   // where your ecommerce engine loops through each item in the cart and
   // prints out _addItem for each
  {foreach $order->items as $item}
  _gaq.push(['_addItem',
    {$order->id},           // order ID - required
    {$item->id},           // SKU/code - required
    {$item->product},        // product name
    {$item->variant},   // category or variation
    {$item->cena},          // unit price - required
    {$item->count}               // quantity - required
  ]);
  {/foreach}
   _gaq.push(['_trackTrans']); //submits transaction to the Analytics servers

  {/if}
	   
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

