<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <meta name="Description" content="" >
    <meta name="Keywords" content="" >
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" >
    <meta name="Distribution" content="Global" >
    <meta name="Author" content="Softweb.cz - www.softweb.cz" >
    <meta name="Robots" content="all, index, follow" >
		<link rel="stylesheet" media="screen,projection,tv" href="{$basePath}/css/admin.css" type="text/css">
		<link rel="stylesheet" media="screen,projection,tv" href="{$basePath}/css/fileuploader.css" type="text/css">
    <title></title>
		<script src="{$basePath}/js/jquery.js" type="text/javascript"></script>
		<script src="{$basePath}/js/jquery.livequery.js" type="text/javascript"></script>
		<script src="{$basePath}/js/jquery.editinplace.0.4.js" type="text/javascript"></script>
		<script src="{$basePath}/js/jquery.nette.js" type="text/javascript"></script>
		<script src="{$basePath}/js/jquery-ui.js" type="text/javascript"></script>
		<script src="{$basePath}/js/datagrid.js" type="text/javascript"></script>
		<script src="{$basePath}/js/fileuploader.js" type="text/javascript"></script>
	</head>
  <body style="margin:0px;padding:0px;">
  {include #iframe}
  </body>
</html>
