{extends '@layout.phtml'}
{block #iframe}
				{snippet table}
					<table id="variants" border="1">
						<tr><th>Název</th><th title="Nákupní cena">NC</th><th title="Prodejní cena">PC</th><th title="Množstevní jednotky">MJ</th><th title="Sklad">Skl.</th></tr>
					{foreach $variants as $variant}
						<tr>
							<td><input class="prop3 prop" style="width:150px !important;" type="text" value="{$variant->jmeno}" onChange="$.post({plink setVariant! 'pid'=>$variant->id},{ jmeno: this.value })"></td>
							<td><input class="prop2" type="text" size="1" value="{$variant->ncena}" onChange="$.post({plink setVariant! 'pid'=>$variant->id},{ ncena: this.value })"></td>
							<td><input class="prop2" type="text" size="1" value="{$variant->cena}" onChange="$.post({plink setVariant! 'pid'=>$variant->id},{ cena: this.value })"></td>
							<td><input class="prop2" type="text" size="1" value="{$variant->kus}" onChange="$.post({plink setVariant! 'pid'=>$variant->id},{ kus: this.value })"></td>
							<td><input class="prop2" type="text" size="1" value="{$variant->sklad}" onChange="$.post({plink setVariant! 'pid'=>$variant->id},{ sklad: this.value })"></td>
						</tr>	
					{/foreach}
						<tr>
							<td><input class="prop3" style="width:150px !important;" type="text" value="" onFocus="$.get({plink addVarRow!})"></td>
							<td><input class="prop2" type="text" size="1" value="" onChange="$.post({plink newVariant!},{ ncena: this.value })"></td>
							<td><input class="prop2" type="text" size="1" value="" onChange="$.post({plink newVariant!},{ cena: this.value })"></td>
							<td><input class="prop2" type="text" size="1" value="" onChange="$.post({plink newVariant!},{ kus: this.value })"></td>
							<td><input class="prop2" type="text" size="1" value="" onChange="$.post({plink newVariant!},{ sklad: this.value })"></td>
						</tr>	
					</table>
	  		<script type="text/javascript">
					$('.prop').last().focus();
				</script>
			{/snippet}
{/block}
