<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <meta name="Description" content="" >
    <meta name="Keywords" content="" >
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" >
    <meta name="Distribution" content="Global" >
    <meta name="Author" content="Softweb.cz - www.softweb.cz" >
    <meta name="Robots" content="all, index, follow" >
    <title></title>
		<script type="text/javascript" src="{$basePath}/ckeditor/ckeditor.js"></script>
	</head>
  <body style="margin:0px;padding:0px;">
  {widget popisNForm, begin}
  {$control['popisNForm']['popis']->control}
  {widget popisNForm, end}
  <script type="text/javascript">
    CKEDITOR.replace( 'popis' ,{
    toolbar: 'MyToolbar',
    height: '157',
    width: '582',
    filebrowserImageBrowseUrl : '../uploader/index.php',
    resize_enabled: false
    });
   </script>
  </body>
</html>
