<!DOCTYPE html>
<html>
  <head>
    <meta name="Description" content="" >
    <meta name="Keywords" content="" >
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" >
    <meta name="Distribution" content="Global" >
    <meta name="Author" content="Softweb.cz - www.softweb.cz" >
    <meta name="Robots" content="all, index, follow" >
    <title>Mercatores - {$title}</title>
		<link rel="stylesheet" media="screen,projection,tv" href="{$basePath}/css/style.css" type="text/css">
		<link rel="stylesheet" type="text/css" href="{$basePath}/css/jquery.lightbox-0.5.css" media="screen" />
		
		<script src="{$basePath}/js/jquery.js" type="text/javascript"></script>
		<script src="{$basePath}/js/jquery.livequery.js" type="text/javascript"></script>
		<script src="{$basePath}/js/jquery.editinplace.0.4.js" type="text/javascript"></script>
		<script src="{$basePath}/js/jquery.nette.js" type="text/javascript"></script>
		<script src="{$basePath}/js/jquery-ui.js" type="text/javascript"></script>
		<script src="{$basePath}/js/netteForms.js" type="text/javascript"></script>
		<script src="{$basePath}/js/jquery.lightbox-0.5.js" type="text/javascript" ></script>
		<script src="{$basePath}/ckeditor/ckeditor.js" type="text/javascript"></script>
  </head>
  <body>
		<div id="page">
			<div id="header">
				<a href="/">
					<img class="left" width="282" height="73" style="filter:progid:DXImageTransform.Microsoft.AlphaImageLoader( src='/images/logo.png'); _width:1px; _height:1; " src="/images/logo.png">
				</a>
				<div class="login">
				</div>
				{include '../Frontend/menu.phtml'}
			</div>
  		<div id="main">
  			<h1>Gratulujeme vám, rozbili jste to!</h1>
				<h2>...a nebo došlo k opravdu závažné chybě</h2>
				<p>
  				<b>Server error 500</b>
  				<br>
  				Na serveru došlo k vnitřní chybě, děláme vše proto, aby byla co nejdříve odstraněna.
  			</p>
  		</div>
  		<div id="footer">
  			<table class="footer">
  				<tr>
  					<td><a href="http://www.landsknechti.cz" target="_blank">www.landsknechti.cz</a> - Landsknechti A.D. 1525</td>
  				</tr>
  				<tr>
  					<td><a href="http://www.livinghistory.cz" target="_blank">www.livinghistory.cz</a> - Český server o "živé historii"</td>
  				</tr>
  				<tr>
  					<td><a href="http://forum.brodec.org" target="_blank">forum.brodec.org</a> - Fórum zabývající se obdobím pozdního středověku</td>
  				</tr>
  				<tr>
  					<td><a href="http://www.arsmaiorum.eu" target="_blank">www.arsmaiorum.eu</a> - Společnost pro zachování a rozvoj evropských bojových umění</td>
  				</tr>
  			</table>
  		</div>
 			<div class="link">
 			 <div style="float:left;width:250px;">
 			 	<a href="http://www.nette.org" target="_blank" title="Tato aplikace je postavena na frameworku Nette"><img src="/images/nette-powered.gif"></a>
 			 	<a href="http://www.dibiphp.com" target="_blank"  title="Tato aplikace je používá databázový layer Dibi"><img src="/images/dibi-powered.gif"></a>
 			 	<a href="http://validator.w3.cz/check?uri={plink '//this'}" target="_blank" title="Tento dokument je validní HTML5"><img src="/images/html5.png" height="14"></a>
 			 </div>
 			 ©2008-2010 Mercatores • Powered by <a href="http://www.softweb.cz" title="tvorba webovýcho stránek">Softweb.cz</a>
  		</div>
    </div>
    <script type="text/javascript">
			var _gaq = _gaq || [];
  		_gaq.push(['_setAccount', 'UA-20217731-2']);
  		_gaq.push(['_trackPageview']);

  		(function() {
    		var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
   			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  		})();
	</script>
  </body>
</html>
