{block #content}
<h1>Kontakt</h1>
<img src="{$baseUri}/images/clary-and-jack.jpg" width="590" style="border:solid 1px black;">
<table class="kontakt">
	<tr>
		<td>
			<p>
			Martin Zadražil<br>
			(Clary Aldringen)
			</p>
			<p>
			Zázvorkova 2006/8<br>
			Praha 13 - Stodůlky<br>
			155 00<br>
			Česká republika
			</p>
			<p>
			Tel.: +420 775 904 582 (Vodafone)<br>
			E-Mail: <a class="odkaz" href="mailto:webmaster@mercatores.cz">webmaster@mercatores.cz</a>
			</p>
			<p>
			IČ: 74901231
			</p>
		</td>
		<td>
			<p>
			Jan Adamčík<br>
			(Gunman Jack)
			</p>
			<p>
			Ptice 10<br>
			okres Praha-západ<br>
			252 18<br>
			Česká republika
			</p>
			<p>
			Tel.: +420 728 866 474 (O2)<br>
			E-Mail:  <a class="odkaz" href="mailto:shop@mercatores.cz">shop@mercatores.cz</a>
			</p>
			<p>
			IČ: 87644819
			</p>
		</td>
	</tr>
</table>
<p id="kontakt">
Pokud se potřebujete rychle na něco zeptat, či nám poslat nějaký vzkaz, můžete využít následující formulář.
Nezapomeňte prosím vyplnit svůj e-mail abychom vám mohli poslat odpověď.
</p>
<div class="kontakt">
{control kontaktForm, begin}
{control kontaktForm, errors}
{$control['kontaktForm']['email']->label}<br>
{$control['kontaktForm']['email']->control}<br>
<br>
{$control['kontaktForm']['message']->label}<br>
{$control['kontaktForm']['message']->control}<br>
<br>
{if isset($showSubmit)}
<div style="text-align:center;">
	{$control['kontaktForm']['send']->control}<br>
</div>
{/if}
<br>
{control kontaktForm, end}
</div>