{block #content}
<h1>Obchodní podmínky</h1>

<h3>Postup objednání</h3>
<p>
Všechny objednávky provádějte pomocí košíku na našich stránkách. Je-li objednávka provedena jiným než uvedeným způsobem, její včasné vyřízení nemůže být zaručeno.
Před první objednávkou se prosím zaregistrujte do databáze Mercatores, která urychlí
a hlavně zjednoduší Vaše další objednávky. Svoje údaje můžete kdykoliv změnit, kliknete-li po přihlášení na své jméno v pravém horním rohu.
K registraci je nezbytné vyplnit stručný přihlašovací formulář. Dbejte na správnost a celistvost uváděných údajů! 
Za nesprávné informace je zodpovědnost a extra výdaje plně na objednavateli. Proto doporučujeme uvádět i nepovinné položky jako telefonní číslo. 
Po zadání vše pečlivě zkontrolujte!
Krátce poté obdržíte potvrzující email s uvedenými údaji. Nyní je možné se přihlásit a pokračovat v objednávce.
Náš systém Vás povede krok za krokem. V případě problémů se prosím obraťte přímo na náš email <a href="mailto:shop@mercatores.cz">shop@mercatores.cz</a>.
Vyžaduje-li výrobek úpravu, specifikaci či jinou podstatnou poznámku (jako barva, velikost, varianta provedení) musí tak být zřetelně a srozumitelně 
doplněno v poznámkách ve finální fázi objednávky. Na pozdější reklamace nebude brán zřetel.
Uzavření objednávky bude potvrzeno rekapitulačním emailem. Dalšími kroky Vás povedeme osobně.
</p><p>
Speciální a zakázkové objednávky posílejte přímo na uvedený <a href="mailto:shop@mercatores.cz">email shop@mercatores.cz</a>.
</p><p>
Dodací lhůta je u každého výrobku specifikována. Provozovatel si však vyhrazuje právo na její změnu po individuální dohodě se zákazníkem. 
V případě, že je výrobek skladem expedujeme do čtyř pracovních dní od obdržení celé platby.
</p>
<h3>Platba</h3>
<p>
Jsou-li výrobky skladem, proveďte po obdržení potvrzujícího emailu a upřesňujících informací platbu dle zvoleného typu (viz. níže) nejpozději do 14 dnů a 
to včetně uvedených distribučních poplatků. Po překročení stanoveného limitu 14 dnů bude objednávka automaticky zrušena.
</p>
<p>
U některých výrobků požadujeme zálohu předem, což je u každého takového výrobku výslovně a zřetelně uvedeno. Objednávky obsahující tyto výrobky 
NEMOHOU být placeny formou dobírky. Záloha je vratná pouze v případě nesplnění závazků z naší strany či neschopnosti jim dostát. (viz. Zrušení objednávky) 
Po uplynutí uvedené výrobní lhůty Vám bude zaslán nový email vyzývající k finálnímu doplatku v předem dohodnuté výši. 
Po obdržení doplatku budou výrobky nejpozději do 1 týdne (není-li řečeno jinak) odeslány.
</p>
<p>
Výjimečné případy budou upřesněny po individuální dohodě.
</p>
<p>
Nabízíme několik forem platby. Je jen na vás, která vám bude vyhovovat více. Rádi vás procesem odesílání povedeme krok za krokem, stačí se zeptat:
</p>

<h5>Dobírka</h5>
<p>
Dobírka je služba provozovaná Českou poštou. V okamžik vyzvednutí balíčku na lokální poště Vám bude předložena složenka s dohodnutou sumou, 
kterou složíte přímo na místě. Cena dobírky je 40 Kč.
</p>
<h5>Bankovní převod</h5>
<p>
Bankovní převod lze provést na pobočkách Vaší banky nebo přes Internet v případě aktivovaného Internet Banking. 
Všechny údaje potřebné pro tuto platbu obdržíte na základě rozpisu ve druhém potvrzujícím emailu. 
Náklady spojené s převodem jsou plně na objednavateli (OUR) a jsou řízeny dle aktuálních tarifů Vašich bank. 
Rádi Vám poradíme se samotným procesem odesílání.
</p>
{*
Western Union
Pobočky Western Union můžete nalézt na poštách, ve směnárnách či v bankovních institucích. Budete-li chtít převézt peníze touto metodou, je třeba si vyzvednout od pracovníka Western Union formulář, který vyplníte kontaktními údaji obdrženými ve druhém potvrzujícím emailu. Po odevzdání vyplněného formuláře a předání odesílaného finančního obnosu (hotovostní platba) obdržíte kód transakce, který zašlete na náš email shop@mercatores.cz . Převodní tarify a další informace můžete nalézt na oficiálních stránkách www.westernunion.com či v ČR na adrese www.intercash.cz.
*}
<h5>Hotovostní platba</h5>
<p>
Týká se pouze historických akcí, na kterých jsme přítomni jako trhovci či aktivní účastníci nebo po individuální dohodě.
</p>
{*
PayPal
PayPal je jednoduchý systém pro provádění finančních transakcí kdekoliv a kdykoliv na světě. Doporučujeme pro svou jednoduchost a poměrně výhodné převodní podmínky. Více na www.paypal.com. Provedení platby není možné bez založení účtu na PayPal!
*}

<h3>Odesílání zboží</h3>

<p>
K odesílání zboží využíváme služeb České pošty a za příplatek po individuální dohodě i kurýrní expresní službu DHL či PPL. 
Přepravné a balné je uvedeno u každé objednávky zvlášť, pro objednávky nad 5000 Kč (250 &euro;) přepravné ZDARMA!
Na expresní a kurýrní služby se akce nevstahuje ani při dosažení stanovené hodnoty.
Doplňující ceny při speciálních objednávkách jako např. větší množství skla a keramiky budou stanoveny po domluvě.
Pro Ameriku a ostatní kontinenty je výše tarifu stanovena po individuální dohodě.
</p><p>
Všechny balíky jsou pojištěny proti ztrátě a poškození do jejich nominální výše.
</p><p>
PROSÍME, ZKONTROLUJTE SI ZBOŽÍ OKAMŽITĚ PO OBDRŽENÍ.
</p>

<h3>Reklamace, záruka a zrušení objednávky</h3>

<h5>Zrušení objednávky</h5>
<p>
Při nedodržení výrobního termínu zakázkových produktů či produktů na objednávku má zákazník právo požadovat zrušení objednávky a vrácení zálohy v plné 
výši není-li předchozí dohodou stanoveno jinak.
</p>

<h5>Záruka</h5>
<p>
Záruka je ze zákona 24 měsíců od data převzetí zboží. Záruka se nevztahuje na mechanické poškození, škody vzniklé nenáležitým používáním či neodpovídající péčí (např. o boty) nebo běžným opotřebením.
Zákazník rovněž může využít lhůtu 21 dní na vrácení zboží bez udání důvodu(zákonem stanovená lhůta je 14 dní), zboží však nesmí být poškozeno a nesmí na něm být patrné známky používání.
</p>

<h5>Reklamace</h5>
<p>
Není-li se zbožím vše v pořádku nebo se v průběhu záruční lhůty stane závada vzniklá skrytou vadou či výrobní chybou, je možné uplatnit reklamaci výrobku/ů. 
Výrobky musí být schopny dalšího prodeje, jinak platí odstavec 7c) paragrafu 53 občanského zákoníku, podle něhož spotřebitel nemůže odstoupit od smlouvy vzhledem k odstavci 6, 
jedná-li se o zboží podlehájící opotřebení.
K reklamovanému zboží musí být přiložen doklad o převzetí či fakturační list s popisem nebo fotodokumentací vzniklé závady, jinak reklamace nebude uznána. 
Vrácené zboží musí být odesláno jako obyčejný balík na naši adresu (viz. Faktura). Vrácená zásilka s dobírkovným nebude uznána. 
Provozovatel obchodu nehradí náklady spojené s dodatečnou přepravou a dobírkovným způsobené reklamací.
Uznaná reklamace bude vyřízena formou opravy, dodání nového výrobku a pokud oprava ani výměna není možná vrácení peněz formou bankovního převodu na 
účet spotřebitele.
Provozovatel si vyhrazuje 30-ti denní vyřizovací lhůtu. Po překročení má zákazník právo na okamžité vrácení peněz.
</p>
<p>
Máte-li nějaké nejasnosti či dotaz, zkontaktujte nás prosím na shop@mercatores.cz.
</p>
<p>
Neznalost obchodních podmínek neomlouvá!
</p>